name: CI Rakuten

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download spaCy model
      run: python -m spacy download fr_core_news_sm

    - name: Download NLTK stopwords
      run: python -c "import nltk; nltk.download('stopwords')"

    - name: Run tests
      run: pytest test_api.py -v